/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Arabic AI Tools Platform API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";
/**
 * Returns server health status
 * @summary Health check
 */
export declare const HealthCheckResponse: zod.ZodObject<{
    status: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
}, {
    status: string;
}>;
/**
 * @summary Summarize Arabic or English text using AI
 */
export declare const summarizeTextBodyLengthDefault = "medium";
export declare const summarizeTextBodyLanguageDefault = "ar";
export declare const SummarizeTextBody: zod.ZodObject<{
    text: zod.ZodString;
    length: zod.ZodDefault<zod.ZodEnum<["short", "medium", "long"]>>;
    language: zod.ZodDefault<zod.ZodEnum<["ar", "en"]>>;
}, "strip", zod.ZodTypeAny, {
    length: "medium" | "short" | "long";
    text: string;
    language: "ar" | "en";
}, {
    text: string;
    length?: "medium" | "short" | "long" | undefined;
    language?: "ar" | "en" | undefined;
}>;
export declare const SummarizeTextResponse: zod.ZodObject<{
    result: zod.ZodString;
    toolUsed: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    result: string;
    toolUsed: string;
}, {
    result: string;
    toolUsed: string;
}>;
/**
 * @summary Generate AI prompts from a topic or idea
 */
export declare const generatePromptBodyStyleDefault = "creative";
export declare const generatePromptBodyCountDefault = 5;
export declare const generatePromptBodyLanguageDefault = "ar";
export declare const GeneratePromptBody: zod.ZodObject<{
    topic: zod.ZodString;
    style: zod.ZodDefault<zod.ZodEnum<["creative", "professional", "educational", "marketing"]>>;
    count: zod.ZodDefault<zod.ZodNumber>;
    language: zod.ZodDefault<zod.ZodEnum<["ar", "en", "both"]>>;
}, "strip", zod.ZodTypeAny, {
    language: "ar" | "en" | "both";
    topic: string;
    style: "creative" | "professional" | "educational" | "marketing";
    count: number;
}, {
    topic: string;
    language?: "ar" | "en" | "both" | undefined;
    style?: "creative" | "professional" | "educational" | "marketing" | undefined;
    count?: number | undefined;
}>;
export declare const GeneratePromptResponse: zod.ZodObject<{
    prompts: zod.ZodArray<zod.ZodString, "many">;
    toolUsed: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    toolUsed: string;
    prompts: string[];
}, {
    toolUsed: string;
    prompts: string[];
}>;
/**
 * @summary Generate social media captions in Arabic
 */
export declare const generateCaptionBodyPlatformDefault = "general";
export declare const generateCaptionBodyToneDefault = "casual";
export declare const generateCaptionBodyCountDefault = 3;
export declare const GenerateCaptionBody: zod.ZodObject<{
    topic: zod.ZodString;
    platform: zod.ZodDefault<zod.ZodEnum<["instagram", "twitter", "tiktok", "linkedin", "general"]>>;
    tone: zod.ZodDefault<zod.ZodEnum<["funny", "professional", "motivational", "casual"]>>;
    count: zod.ZodDefault<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    topic: string;
    count: number;
    platform: "general" | "instagram" | "twitter" | "tiktok" | "linkedin";
    tone: "professional" | "casual" | "funny" | "motivational";
}, {
    topic: string;
    count?: number | undefined;
    platform?: "general" | "instagram" | "twitter" | "tiktok" | "linkedin" | undefined;
    tone?: "professional" | "casual" | "funny" | "motivational" | undefined;
}>;
export declare const GenerateCaptionResponse: zod.ZodObject<{
    captions: zod.ZodArray<zod.ZodString, "many">;
    hashtags: zod.ZodArray<zod.ZodString, "many">;
    toolUsed: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    toolUsed: string;
    captions: string[];
    hashtags: string[];
}, {
    toolUsed: string;
    captions: string[];
    hashtags: string[];
}>;
/**
 * @summary Get AI homework help for a question
 */
export declare const homeworkHelpBodySubjectDefault = "general";
export declare const homeworkHelpBodyLanguageDefault = "ar";
export declare const HomeworkHelpBody: zod.ZodObject<{
    question: zod.ZodString;
    subject: zod.ZodDefault<zod.ZodEnum<["math", "science", "arabic", "english", "history", "geography", "general"]>>;
    grade: zod.ZodOptional<zod.ZodString>;
    language: zod.ZodDefault<zod.ZodEnum<["ar", "en"]>>;
}, "strip", zod.ZodTypeAny, {
    language: "ar" | "en";
    question: string;
    subject: "general" | "math" | "science" | "arabic" | "english" | "history" | "geography";
    grade?: string | undefined;
}, {
    question: string;
    language?: "ar" | "en" | undefined;
    subject?: "general" | "math" | "science" | "arabic" | "english" | "history" | "geography" | undefined;
    grade?: string | undefined;
}>;
export declare const HomeworkHelpResponse: zod.ZodObject<{
    result: zod.ZodString;
    toolUsed: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    result: string;
    toolUsed: string;
}, {
    result: string;
    toolUsed: string;
}>;
/**
 * @summary Convert Arabic or English text to emoji representation
 */
export declare const textToEmojiBodyLanguageDefault = "ar";
export declare const TextToEmojiBody: zod.ZodObject<{
    text: zod.ZodString;
    language: zod.ZodDefault<zod.ZodEnum<["ar", "en", "both"]>>;
}, "strip", zod.ZodTypeAny, {
    text: string;
    language: "ar" | "en" | "both";
}, {
    text: string;
    language?: "ar" | "en" | "both" | undefined;
}>;
export declare const TextToEmojiResponse: zod.ZodObject<{
    result: zod.ZodString;
    toolUsed: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    result: string;
    toolUsed: string;
}, {
    result: string;
    toolUsed: string;
}>;
/**
 * @summary Generate a professional Arabic CV/Resume
 */
export declare const generateResumeBodyLanguageDefault = "ar";
export declare const GenerateResumeBody: zod.ZodObject<{
    name: zod.ZodString;
    jobTitle: zod.ZodString;
    summary: zod.ZodOptional<zod.ZodString>;
    experience: zod.ZodOptional<zod.ZodString>;
    education: zod.ZodOptional<zod.ZodString>;
    skills: zod.ZodOptional<zod.ZodString>;
    language: zod.ZodDefault<zod.ZodEnum<["ar", "en"]>>;
}, "strip", zod.ZodTypeAny, {
    language: "ar" | "en";
    name: string;
    jobTitle: string;
    summary?: string | undefined;
    experience?: string | undefined;
    education?: string | undefined;
    skills?: string | undefined;
}, {
    name: string;
    jobTitle: string;
    language?: "ar" | "en" | undefined;
    summary?: string | undefined;
    experience?: string | undefined;
    education?: string | undefined;
    skills?: string | undefined;
}>;
export declare const GenerateResumeResponse: zod.ZodObject<{
    html: zod.ZodString;
    text: zod.ZodString;
    toolUsed: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    text: string;
    toolUsed: string;
    html: string;
}, {
    text: string;
    toolUsed: string;
    html: string;
}>;
/**
 * @summary Get platform statistics (total tool uses, trending tools)
 */
export declare const GetToolStatsResponse: zod.ZodObject<{
    totalUses: zod.ZodNumber;
    totalTools: zod.ZodNumber;
    trending: zod.ZodArray<zod.ZodObject<{
        toolId: zod.ZodString;
        name: zod.ZodString;
        uses: zod.ZodNumber;
        trending: zod.ZodBoolean;
    }, "strip", zod.ZodTypeAny, {
        name: string;
        trending: boolean;
        toolId: string;
        uses: number;
    }, {
        name: string;
        trending: boolean;
        toolId: string;
        uses: number;
    }>, "many">;
}, "strip", zod.ZodTypeAny, {
    totalUses: number;
    totalTools: number;
    trending: {
        name: string;
        trending: boolean;
        toolId: string;
        uses: number;
    }[];
}, {
    totalUses: number;
    totalTools: number;
    trending: {
        name: string;
        trending: boolean;
        toolId: string;
        uses: number;
    }[];
}>;
/**
 * @summary List all conversations
 */
export declare const ListOpenaiConversationsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    title: zod.ZodString;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    title: string;
    createdAt: Date;
}, {
    id: number;
    title: string;
    createdAt: Date;
}>;
export declare const ListOpenaiConversationsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    title: zod.ZodString;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    title: string;
    createdAt: Date;
}, {
    id: number;
    title: string;
    createdAt: Date;
}>, "many">;
/**
 * @summary Create a new conversation
 */
export declare const CreateOpenaiConversationBody: zod.ZodObject<{
    title: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    title: string;
}, {
    title: string;
}>;
/**
 * @summary Get conversation with messages
 */
export declare const GetOpenaiConversationParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetOpenaiConversationResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    title: zod.ZodString;
    createdAt: zod.ZodDate;
    messages: zod.ZodArray<zod.ZodObject<{
        id: zod.ZodNumber;
        conversationId: zod.ZodNumber;
        role: zod.ZodString;
        content: zod.ZodString;
        createdAt: zod.ZodDate;
    }, "strip", zod.ZodTypeAny, {
        id: number;
        createdAt: Date;
        conversationId: number;
        role: string;
        content: string;
    }, {
        id: number;
        createdAt: Date;
        conversationId: number;
        role: string;
        content: string;
    }>, "many">;
}, "strip", zod.ZodTypeAny, {
    id: number;
    title: string;
    createdAt: Date;
    messages: {
        id: number;
        createdAt: Date;
        conversationId: number;
        role: string;
        content: string;
    }[];
}, {
    id: number;
    title: string;
    createdAt: Date;
    messages: {
        id: number;
        createdAt: Date;
        conversationId: number;
        role: string;
        content: string;
    }[];
}>;
/**
 * @summary Delete a conversation
 */
export declare const DeleteOpenaiConversationParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
/**
 * @summary List messages in a conversation
 */
export declare const ListOpenaiMessagesParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const ListOpenaiMessagesResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    conversationId: zod.ZodNumber;
    role: zod.ZodString;
    content: zod.ZodString;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    createdAt: Date;
    conversationId: number;
    role: string;
    content: string;
}, {
    id: number;
    createdAt: Date;
    conversationId: number;
    role: string;
    content: string;
}>;
export declare const ListOpenaiMessagesResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    conversationId: zod.ZodNumber;
    role: zod.ZodString;
    content: zod.ZodString;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    createdAt: Date;
    conversationId: number;
    role: string;
    content: string;
}, {
    id: number;
    createdAt: Date;
    conversationId: number;
    role: string;
    content: string;
}>, "many">;
/**
 * @summary Send a text message and receive a streaming text response
 */
export declare const SendOpenaiMessageParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const SendOpenaiMessageBody: zod.ZodObject<{
    content: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    content: string;
}, {
    content: string;
}>;
//# sourceMappingURL=api.d.ts.map