/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Arabic AI Tools Platform API
 * OpenAPI spec version: 0.1.0
 */
export type CaptionInputTone = (typeof CaptionInputTone)[keyof typeof CaptionInputTone];
export declare const CaptionInputTone: {
    readonly funny: "funny";
    readonly professional: "professional";
    readonly motivational: "motivational";
    readonly casual: "casual";
};
//# sourceMappingURL=captionInputTone.d.ts.map