/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Arabic AI Tools Platform API
 * OpenAPI spec version: 0.1.0
 */
export interface CaptionsResult {
    captions: string[];
    hashtags: string[];
    toolUsed: string;
}
//# sourceMappingURL=captionsResult.d.ts.map