/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Arabic AI Tools Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { CaptionInputPlatform } from "./captionInputPlatform";
import type { CaptionInputTone } from "./captionInputTone";

export interface CaptionInput {
  topic: string;
  platform?: CaptionInputPlatform;
  tone?: CaptionInputTone;
  count?: number;
}
