/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Arabic AI Tools Platform API
 * OpenAPI spec version: 0.1.0
 */

export type HomeworkInputLanguage =
  (typeof HomeworkInputLanguage)[keyof typeof HomeworkInputLanguage];

export const HomeworkInputLanguage = {
  ar: "ar",
  en: "en",
} as const;
