/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Arabic AI Tools Platform API
 * OpenAPI spec version: 0.1.0
 */
export type HomeworkInputSubject = (typeof HomeworkInputSubject)[keyof typeof HomeworkInputSubject];
export declare const HomeworkInputSubject: {
    readonly math: "math";
    readonly science: "science";
    readonly arabic: "arabic";
    readonly english: "english";
    readonly history: "history";
    readonly geography: "geography";
    readonly general: "general";
};
//# sourceMappingURL=homeworkInputSubject.d.ts.map