/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Arabic AI Tools Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { HomeworkInputLanguage } from "./homeworkInputLanguage";
import type { HomeworkInputSubject } from "./homeworkInputSubject";
export interface HomeworkInput {
    question: string;
    subject?: HomeworkInputSubject;
    grade?: string;
    language?: HomeworkInputLanguage;
}
//# sourceMappingURL=homeworkInput.d.ts.map