/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Arabic AI Tools Platform API
 * OpenAPI spec version: 0.1.0
 */
export * from "./apiError";
export * from "./captionInput";
export * from "./captionInputPlatform";
export * from "./captionInputTone";
export * from "./captionsResult";
export * from "./healthStatus";
export * from "./homeworkInput";
export * from "./homeworkInputLanguage";
export * from "./homeworkInputSubject";
export * from "./openaiConversation";
export * from "./openaiConversationInput";
export * from "./openaiConversationWithMessages";
export * from "./openaiError";
export * from "./openaiMessage";
export * from "./openaiMessageInput";
export * from "./platformStats";
export * from "./promptInput";
export * from "./promptInputLanguage";
export * from "./promptInputStyle";
export * from "./promptsResult";
export * from "./resumeInput";
export * from "./resumeInputLanguage";
export * from "./resumeResult";
export * from "./summarizeInput";
export * from "./summarizeInputLanguage";
export * from "./summarizeInputLength";
export * from "./textInput";
export * from "./textInputLanguage";
export * from "./textResult";
export * from "./toolStat";
//# sourceMappingURL=index.d.ts.map