/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Arabic AI Tools Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { ToolStat } from "./toolStat";
export interface PlatformStats {
    totalUses: number;
    totalTools: number;
    trending: ToolStat[];
}
//# sourceMappingURL=platformStats.d.ts.map