/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Arabic AI Tools Platform API
 * OpenAPI spec version: 0.1.0
 */
export type PromptInputStyle = (typeof PromptInputStyle)[keyof typeof PromptInputStyle];
export declare const PromptInputStyle: {
    readonly creative: "creative";
    readonly professional: "professional";
    readonly educational: "educational";
    readonly marketing: "marketing";
};
//# sourceMappingURL=promptInputStyle.d.ts.map