/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Arabic AI Tools Platform API
 * OpenAPI spec version: 0.1.0
 */
export type PromptInputLanguage = (typeof PromptInputLanguage)[keyof typeof PromptInputLanguage];
export declare const PromptInputLanguage: {
    readonly ar: "ar";
    readonly en: "en";
    readonly both: "both";
};
//# sourceMappingURL=promptInputLanguage.d.ts.map