/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Arabic AI Tools Platform API
 * OpenAPI spec version: 0.1.0
 */

export type PromptInputLanguage =
  (typeof PromptInputLanguage)[keyof typeof PromptInputLanguage];

export const PromptInputLanguage = {
  ar: "ar",
  en: "en",
  both: "both",
} as const;
