/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Arabic AI Tools Platform API
 * OpenAPI spec version: 0.1.0
 */
import type { ResumeInputLanguage } from "./resumeInputLanguage";

export interface ResumeInput {
  name: string;
  jobTitle: string;
  summary?: string;
  experience?: string;
  education?: string;
  skills?: string;
  language?: ResumeInputLanguage;
}
