/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Arabic AI Tools Platform API
 * OpenAPI spec version: 0.1.0
 */

export type SummarizeInputLanguage =
  (typeof SummarizeInputLanguage)[keyof typeof SummarizeInputLanguage];

export const SummarizeInputLanguage = {
  ar: "ar",
  en: "en",
} as const;
