import { FileText, Sparkles, Image, GraduationCap, Smile, FileBadge, QrCode, KeyRound, Gamepad2, FileDown, Languages, RefreshCw, Mail, Calculator, BookOpen } from "lucide-react";
import type { TranslationKey } from "./i18n";

export const TOOL_CATEGORY_KEYS: { id: string; labelKey: TranslationKey }[] = [
  { id: "all", labelKey: "catAll" },
  { id: "ai", labelKey: "catAI" },
  { id: "productivity", labelKey: "catProductivity" },
  { id: "social", labelKey: "catSocial" },
  { id: "education", labelKey: "catEducation" },
  { id: "utilities", labelKey: "catUtilities" },
];

export const TOOLS: {
  id: string;
  titleKey: TranslationKey;
  descKey: TranslationKey;
  icon: React.ElementType;
  href: string;
  category: string;
  color: string;
  bg: string;
}[] = [
  {
    id: "summarize",
    titleKey: "toolSummarize",
    descKey: "toolSummarizeDesc",
    icon: FileText,
    href: "/summarize",
    category: "ai",
    color: "text-blue-400",
    bg: "bg-blue-500/10",
  },
  {
    id: "generate-prompt",
    titleKey: "toolPrompt",
    descKey: "toolPromptDesc",
    icon: Sparkles,
    href: "/generate-prompt",
    category: "ai",
    color: "text-purple-400",
    bg: "bg-purple-500/10",
  },
  {
    id: "generate-caption",
    titleKey: "toolCaption",
    descKey: "toolCaptionDesc",
    icon: Image,
    href: "/generate-caption",
    category: "social",
    color: "text-pink-400",
    bg: "bg-pink-500/10",
  },
  {
    id: "homework-help",
    titleKey: "toolHomework",
    descKey: "toolHomeworkDesc",
    icon: GraduationCap,
    href: "/homework-help",
    category: "education",
    color: "text-emerald-400",
    bg: "bg-emerald-500/10",
  },
  {
    id: "text-to-emoji",
    titleKey: "toolEmoji",
    descKey: "toolEmojiDesc",
    icon: Smile,
    href: "/text-to-emoji",
    category: "social",
    color: "text-yellow-400",
    bg: "bg-yellow-500/10",
  },
  {
    id: "generate-resume",
    titleKey: "toolResume",
    descKey: "toolResumeDesc",
    icon: FileBadge,
    href: "/generate-resume",
    category: "productivity",
    color: "text-indigo-400",
    bg: "bg-indigo-500/10",
  },
  {
    id: "translate",
    titleKey: "toolTranslate",
    descKey: "toolTranslateDesc",
    icon: Languages,
    href: "/summarize",
    category: "ai",
    color: "text-cyan-400",
    bg: "bg-cyan-500/10",
  },
  {
    id: "paraphrase",
    titleKey: "toolParaphrase",
    descKey: "toolParaphraseDesc",
    icon: RefreshCw,
    href: "/summarize",
    category: "ai",
    color: "text-violet-400",
    bg: "bg-violet-500/10",
  },
  {
    id: "email-writer",
    titleKey: "toolEmailWriter",
    descKey: "toolEmailWriterDesc",
    icon: Mail,
    href: "/summarize",
    category: "productivity",
    color: "text-amber-400",
    bg: "bg-amber-500/10",
  },
  {
    id: "math-solver",
    titleKey: "toolMathSolver",
    descKey: "toolMathSolverDesc",
    icon: Calculator,
    href: "/homework-help",
    category: "education",
    color: "text-green-400",
    bg: "bg-green-500/10",
  },
  {
    id: "story-writer",
    titleKey: "toolStoryWriter",
    descKey: "toolStoryWriterDesc",
    icon: BookOpen,
    href: "/generate-prompt",
    category: "ai",
    color: "text-rose-400",
    bg: "bg-rose-500/10",
  },
  {
    id: "qr-generator",
    titleKey: "toolQR",
    descKey: "toolQRDesc",
    icon: QrCode,
    href: "/qr-generator",
    category: "utilities",
    color: "text-zinc-400",
    bg: "bg-zinc-500/10",
  },
  {
    id: "password-generator",
    titleKey: "toolPassword",
    descKey: "toolPasswordDesc",
    icon: KeyRound,
    href: "/password-generator",
    category: "utilities",
    color: "text-red-400",
    bg: "bg-red-500/10",
  },
  {
    id: "free-fire-names",
    titleKey: "toolGameNames",
    descKey: "toolGameNamesDesc",
    icon: Gamepad2,
    href: "/free-fire-names",
    category: "social",
    color: "text-orange-400",
    bg: "bg-orange-500/10",
  },
  {
    id: "image-to-pdf",
    titleKey: "toolImagePDF",
    descKey: "toolImagePDFDesc",
    icon: FileDown,
    href: "/image-to-pdf",
    category: "productivity",
    color: "text-teal-400",
    bg: "bg-teal-500/10",
  },
];
